# Generated by Django 5.1.2 on 2024-10-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('c', models.FloatField()),
                ('root1', models.FloatField(blank=True, null=True)),
                ('root2', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
