# Generated by Django 5.1.2 on 2024-10-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
    ]
